name: films_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0-nullsafety.2
  freezed_annotation: ^0.14.2
  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.0.1
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  google_sign_in: ^5.0.4
  injectable: ^1.4.1
  get_it: ^7.1.4
  provider: ^5.0.0
  uuid: ^3.0.4
  auto_route: ^2.2.0
  json_annotation: ^4.0.1
  rxdart: ^0.27.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  lint: ^1.5.3
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.3


analyzer: ^2.0.0
    
flutter:
  uses-material-design: true

